name: Publish VS Code Extension

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Install vsce
      run: npm install -g vsce

    - name: Install dependencies
      run: npm ci

    - name: Update version in package.json
      run: |
        VERSION=${{ github.event.release.tag_name }}
        jq '.version = "'${VERSION#v}'"' package.json > tmp.json && mv tmp.json package.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b release/$VERSION
        git add .
        git commit -m "Update version to $VERSION"
        git push origin release/$VERSION

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Release ${{ github.event.release.tag_name }}
        branch: release/${{ github.event.release.tag_name }}
        base: master

    - name: Merge PR
      run: |
        MERGE_RESPONSE=$(curl -s -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}/merge \
          -d '{
            "commit_title": "Merge release '${{ github.event.release.tag_name }}'"
          }')
        echo $MERGE_RESPONSE
      id: merge_pr

    - name: Run latest-tag
      uses: EndBug/latest-tag@v1.5.1
      with:
        force-branch: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update release
      run: |
        curl \
          -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
          -d '{
            "target_commitish": "master"
          }'

    - name: Package and publish extension
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      run: vsce publish -p $VSCE_TOKEN
