name: Publish VS Code Extension

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install vsce
      run: npm install -g vsce

    - name: Install dependencies
      run: npm ci

    - name: Package and publish extension
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      run: vsce publish -p $VSCE_TOKEN

    - name: Apply latest tag
      run: |
        git tag -fa @latest -m "Update @latest tag"
        git push origin @latest